### ISSUE TITLE
Flow release finish not working

### ISSUE THREAD

**Issue by ramiel** [timbrel/GitSavvy#279]
When I launch git flow release finish from the plugin, it switch to the terminal but this error is shown

```
Switched to branch 'master'
error: Terminal is dumb, but EDITOR unset
Please supply the message using either -m or -F option.
Fatal: Tagging failed. Please run finish again to retry.
```

Is a problem with this plugin or with my system configuration?

**Comment by divmain** [comment]
Git flow is the one piece of GitSavvy I didn't put together :) @asfaltboy, can you comment?

**Comment by asfaltboy** [comment]
@ramiel I can't really tell without seeing your branches. Help me help you with some questions:

1. Copy paste the output the following commands:
  * `$ git config -l | grep flow`
  * `$ git branch -va | grep feature`
2. Which branch are you on when you issue the `release finish` command?
3. What happens when you issue the same directly in command line: `git flow release finish`?
4. Which version of `git-flow` do you use, and where did you install it from?

**Comment by ramiel** [comment]
So, here the informations:
```bash
$ git config -l | grep flow
gitflow.branch.master=master
gitflow.branch.develop=develop
gitflow.prefix.feature=feature/
gitflow.prefix.release=release/
gitflow.prefix.hotfix=hotfix/
gitflow.prefix.support=support/
gitflow.prefix.versiontag=
gitflow.path.hooks=/home/fabrizio/Modelli/Projects/doc-ci/instructor/.git/hooks
```
then

```bash
$ git branch -va | grep feature
feature/extractors     57ad4dd Ignored local configuration
```

The version of git-flow is `1.8.0 (AVH Edition)`.
When I try to close the release I'm on the release branch itself.
Doing the same on the console actually close the branch (show me three commit message, two for the merges and and for the tag)

**Comment by asfaltboy** [comment]
To be honest I have not been aware of the AVH version up to this moment. Our current implementation was built to work with nvie's git-flow (requiring 0.4.1 or up), which is what I'm using, but I don't think the fork is the reason.

I installed latest git-flow-avh (1.9 from homebrew) but could not reproduce your issue. Looking again at your error, the message seems to indicate that the `EDITOR` environment variable must be set (`release finish` requires a message for a tag commit), when executing commands the way we do (IIRC using `subprocess.Popen`).

Can you try setting, for instance, `EDITOR=vi` in your profile, running sublime from that profile and then executing the command again? Alternatively, set the editor of your choice in [`git config`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration), e.g:

    git config core.editor=mvim -f

Also, it's worth noting that [SublimeGit had/have a similar issue](https://github.com/SublimeGit/SublimeGit/issues/51), and I'm not sure how they solve it. Is opening a view in sublime to record the message from use a good solution (similarly to commit)?

**Comment by asfaltboy** [comment]
@divmain How do you feel about this? A `release/hotfix finish` by default requires a message to be added (to be used when creating the tag). However a commit for a tag it is not required, so it could be skipped. Alternatively, we could optionally enter the commit message for the tag in sublime, prior to using `git flow release finish`.

**Comment by divmain** [comment]
Has someone documented/published the "git flow way" in a blog post or something?  As I mentioned, I don't use it in my workflow, and that may make it difficult to support multiple possible variants of git flow.  However, as a general rule, I'd aim to be as permissible as possible.  In this case, it may mean always doing `flow release` in an AVH-compatible manner - so possibly always prompt for a message, even if it is not required for nvie's git flow.  Does that make sense?

**Comment by asfaltboy** [comment]
Here is Vincent's [original blog post](http://nvie.com/posts/a-successful-git-branching-model/) that "started it all". In fact the blog, as well as both `AVS` and `nvie` versions use an annotated tag by default (`git tag -a <ver>`) when [finishing a release](http://nvie.com/posts/a-successful-git-branching-model/#finishing-a-release-branch).

The default in git-flow is to display an editor for the [annotated tag message](https://git-scm.com/book/en/v2/Git-Basics-Tagging#Annotated-Tags). However, git-flow (both versions) currently calls the configured editor, which may not be even configured, as the case with this issue.
An external editor (say `gvim`) called from our subprocess can also cause sublime to freeze, as has happened to me a few times.

So, do you think a one-liner sublime prompt for a tag annotation it's enough? Or do we need to build something larger like the commit view?

**Comment by ramiel** [comment]
If you want my humble opinion, people expects a commit window for the annotated tag.

**Comment by divmain** [comment]
@asfaltboy - any more thoughts about this?  I'm fine adding something similar to the commit view (there is already a UI primitive to use for this, which is used for amending commits).  But since I'm not a `flow` user, I'm not sure of the best way forward with this.  @ramiel, if you're still using GitSavvy and this is an important issue for you, I'd welcome a PR from you also.

**Comment by asfaltboy** [comment]
This raises a question on where are long/short prompts appropriate. In other words, I don't see this as a "flow" problem only; this applies to any `git` command that prompts for input in an editor, (such as creating a tag would).

For example, in the `Create Tag` command, we already prompt for tag commit message in the subject line, so technically we could easily do that here too. However, people may want to / used to commit a longer tag description using the commit view, listing e.g. version release notes.

So my suggestion is try implement a simple switch (perhaps defined in settings), for which prompt to display in some commands. I could imagine some users wanting to use short commit messages for regular commits too, perhaps being used to single line `git commit -m "message"` invocation.

I'd also extract the prompting methods into a resuable mixin and use were appropriate.

**Comment by mufeed20** [comment]
Hi,  
Has this been fixed yet? I'm a flow user and just started really using Git. I normally use SmartGit because its fast but having to always switch away from Sublime Text is just a hiccup in my workflow in both Github repositories and others. I believe this must be fixed by now and you just forgot to close the issue.  
Thank you for your works!

**Comment by asfaltboy** [comment]
@mufeed20 thanks for the reminder, actually this wasn't fixed yet!

I completely forgot about fixing this, which is silly, since I myself resort to switching to shell to finish a release. Will try to resolve this weekend, thanks!

**Comment by mufeed20** [comment]
What would be the workaround? Just set EDITOR to 'subl3' ?
Thanks again.

**Comment by asfaltboy** [comment]
To be honest, I simply use shell right now, and I found `EDITOR=vi` works well. Not sure if sublime works as editor by default, but you can try and let us know.

**Comment by asfaltboy** [comment]
Unfortunately it doesn't seem like there's a way to pass the messages to the `git-flow` tool.

This means that if we wanted to implement this part of git-flow correctly, we'd need to write our own implementation that will, if we follow nvie's app output, do the following:

> Summary of actions:
> - Latest objects have been fetched from 'origin'
> - Release branch has been merged into 'master'
> - The release was tagged '0.0'
> - Release branch has been back-merged into 'develop'
> - Release branch 'release/0.0' has been deleted

**Comment by kaste** [comment]
I think I fixed that some time ago.
